"""add condition to vehicles

Revision ID: fe2a9887841c
Revises: d1be31a31ce3
Create Date: 2026-04-24 19:51:13.670286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe2a9887841c'
down_revision: Union[str, Sequence[str], None] = 'd1be31a31ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('condition', sa.String(), nullable=False, server_default='used'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'condition')
    # ### end Alembic commands ###
